FROM python:stretch

RUN echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list && apt-get update && apt-get install patchelf ccache

WORKDIR /app
VOLUME /root/.cache/Nuitka
RUN pip install numpy Pillow nuitka paho-mqtt
